//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppGallineros.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class detgallinasgallineros
    {
        public int id { get; set; }
        public int Gallinas_Id { get; set; }
        public int Gallineros_Id { get; set; }
        public int Granjas_Id { get; set; }
        public int StatusGallina_Id { get; set; }
    
        public virtual gallinas gallinas { get; set; }
        public virtual gallineros gallineros { get; set; }
        public virtual granjas granjas { get; set; }
        public virtual statusgallina statusgallina { get; set; }
    }
}
