//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppGallineros.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3F19C_gallinerosEntities : DbContext
    {
        public DB_A3F19C_gallinerosEntities()
            : base("name=DB_A3F19C_gallinerosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<detproducciongallineros> detproducciongallineros { get; set; }
        public virtual DbSet<gallineros> gallineros { get; set; }
        public virtual DbSet<granjas> granjas { get; set; }
        public virtual DbSet<granjeros> granjeros { get; set; }
        public virtual DbSet<produccion> produccion { get; set; }
        public virtual DbSet<reporte> reporte { get; set; }
        public virtual DbSet<statusgallina> statusgallina { get; set; }
        public virtual DbSet<detgallinasgallineros> detgallinasgallineros { get; set; }
        public virtual DbSet<gallinas> gallinas { get; set; }
        public virtual DbSet<detreportegallinas> detreportegallinas { get; set; }
    }
}
